name: dart_init
description: Easy create dart_project
version: 0.0.1
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart_init

executables:
  dart_init: main

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.5.2
  path: ^1.6.2

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
